version: "3.9"

services:

  backend:
    build: ./backend
    container_name: openrouter-backend

    ports:
      - "3000:3000"

    env_file:
      - ./backend/.env

    depends_on:
      - postgres
      - redis

    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: openrouter-frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

    volumes:
      - ./frontend:/app
      - /app/node_modules

  postgres:
    image: postgres:17-alpine

    container_name: openrouter-postgres

    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

    container_name: openrouter-redis

    restart: always

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

volumes:

  postgres_data:

  redis_data: